import React, { useCallback, useState } from "react"
import PropTypes from "prop-types"
import ReactOnRails from 'react-on-rails'

import * as styles from './RockPaperScissors.module.css'

import Rock from './Rock.svg'
import Paper from './Paper.svg'
import Scissors from './Scissors.svg'

const Choice = ({ image, imageHeight, label, onClick, value }) => {
  return (
    <div className={styles.choice} onClick={() => onClick(value)}>
      <img src={image} height={imageHeight} />
      <div className={styles.choiceLabel}>{label}</div>
    </div>
  )
}

const RockPaperScissors = () => {
  const [selected, setSelected] = useState(null)
  const [data, setData] = useState(null)
  const [isLoading, setIsLoading] = useState(false)

  const handleChoice = useCallback((choice) => {
    setSelected(choice)
    console.log(choice)

    // reads from DOM csrf token generated by Rails in <%= csrf_meta_tags %>
    const csrfToken = ReactOnRails.authenticityToken();
    const headers = ReactOnRails.authenticityHeaders({ 'Content-Type': 'application/json' });

    setIsLoading(true)
    fetch('http://localhost:3000/games.json', { method: "POST", headers, body: JSON.stringify({ choice }) })
      .then((response) => response.json())
      .then((json) => {
        setData(json)
        setIsLoading(false)
      })
      .catch((error) => console.error(error))
  }, [setSelected])

  console.log('data', data)

  return (
    <React.Fragment>
      <div className={styles.container}>
        <div className={styles.header}>ROCK – PAPER – SCISSORS</div>
        <div className={styles.description}>
          Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no tools. The idea is to make shapes with an outstretched hand where each shape will have a certain degree of power and will lead to an outcome.
        </div>
        <div className={styles.cta}>SELECT YOUR BET</div>
        <div className={styles.choiceContainer}>
          <Choice
            image={Rock}
            imageHeight={139}
            label="Rock"
            onClick={handleChoice}
            value="rock"
          />
          <Choice
            image={Paper}
            imageHeight={161}
            label="Paper"
            onClick={handleChoice}
            value="paper"
          />
          <Choice
            image={Scissors}
            imageHeight={160}
            label="Scissors"
            onClick={handleChoice}
            value="scissors"
          />
        </div>
      </div>
    </React.Fragment>
  )
}

export default RockPaperScissors
